### ISSUE TITLE
found version 4, expected 3, resolving symbol

### ISSUE THREAD

**Issue by anandchakru** [MurhafSousli/ngx-sharebuttons#200]
Please upgrade support for angular v4
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X ] feature request
- [ ] question
```

### OS and Version?
Linux (Ubuntu 16).

### Versions
```
Angular CLI: 1.6.0
Node: 9.2.1
OS: linux x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.3.4
webpack: 3.10.0
```

### Repro steps
Add ShareModule.forRoot()
Include public share: ShareButtons
and accompanying html to the template
run `ng serve`

### The log given by the failure
ERROR in Error: Metadata version mismatch for module /home/uname/workspace/app-name/node_modules/@ngx-share/core/ngx-share-core.d.ts, found version 4, expected 3, resolving symbol AppModule in /home/uname/workspace/app-name/src/app/app.module.ts, resolving symbol AppModule in /home/uname/workspace/app-name/src/app/app.module.ts, resolving symbol AppModule in /home/uname/workspace/app-name/src/app/app.module.ts
    at syntaxError (/home/uname/workspace/app-name/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/uname/workspace/app-name/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/home/uname/workspace/app-name/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/home/uname/workspace/app-name/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/home/uname/workspace/app-name/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/uname/workspace/app-name/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/home/uname/workspace/app-name/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/uname/workspace/app-name/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/uname/workspace/app-name/node_modules/@ngtools/webpack/src/plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/uname/workspace/app-name/node_modules/@ngtools/webpack/src/plugin.js:495:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

### Desired functionality
Increment angular v4 support

**Comment by MurhafSousli** [comment]
dup #192 #190 #199, For angular 4, use version 3 `npm i ngx-sharebuttons@3.0.0`, its documentation is here https://github.com/MurhafSousli/ngx-sharebuttons/wiki
