### ISSUE TITLE
Errors when running in environment with SSR

### ISSUE THREAD

**Issue by Tatenda** [MurhafSousli/ngx-sharebuttons#211]
### Bug Report or Feature Request (mark with an `x`)

- [x] bug report 
- [ ] feature request
- [ ] question

### OS and Version?
Windows 10, OS: win32 x64

### Versions
Angular CLI: 1.6.5
Node: 6.11.5
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.5
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.4.2
webpack-node-externals: 1.6.0
webpack: 3.10.0

### Repro steps
Implement Single Share Button in environment running Angular-Universal for Server Side Rendering.

### The log given by the failure
ERROR { Error: Uncaught (in promise): ReferenceError: navigator is not defined
ReferenceError: navigator is not defined
    at getOS (C:\mynodeprojects\mean_project_start\node_modules\@ngx-share\core\bundles\ngx-share-core.umd.js:548:78)
    at new ShareButtons (C:\mynodeprojects\mean_project_start\node_modules\@ngx-share\core\bundles\ngx-share-core.umd.js:416:19)
    at ShareButtonsFactory (C:\mynodeprojects\mean_project_start\node_modules\@ngx-share\button\bundles\ngx-share-button.umd.js:137:12)
    at _callFactory (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:10948:20)
    at _createProviderInstance$1 (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:10900:26)
    at resolveNgModuleDep (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:10882:17)
    at NgModuleRef_.get (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:12119:16)
    at resolveDep (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:12609:45)
    at createClass (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:12471:29)
    at createDirectiveInstance (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:12316:37)
    at resolvePromise (C:\mynodeprojects\mean_project_start\node_modules\zone.js\dist\zone-node.js:809:31)
    at resolvePromise (C:\mynodeprojects\mean_project_start\node_modules\zone.js\dist\zone-node.js:775:17)
    at C:\mynodeprojects\mean_project_start\node_modules\zone.js\dist\zone-node.js:858:17
    at ZoneDelegate.invokeTask (C:\mynodeprojects\mean_project_start\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:4763:33)
    at ZoneDelegate.invokeTask (C:\mynodeprojects\mean_project_start\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (C:\mynodeprojects\mean_project_start\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (C:\mynodeprojects\mean_project_start\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (C:\mynodeprojects\mean_project_start\node_modules\zone.js\dist\zone-node.js:500:21)
    at Server.ZoneTask.invoke (C:\mynodeprojects\mean_project_start\node_modules\zone.js\dist\zone-node.js:485:48)
  rejection:
   ReferenceError: navigator is not defined
       at getOS (C:\mynodeprojects\mean_project_start\node_modules\@ngx-share\core\bundles\ngx-share-core.umd.js:548:78)
       at new ShareButtons (C:\mynodeprojects\mean_project_start\node_modules\@ngx-share\core\bundles\ngx-share-core.umd.js:416:19)
       at ShareButtonsFactory (C:\mynodeprojects\mean_project_start\node_modules\@ngx-share\button\bundles\ngx-share-button.umd.js:137:12)
       at _callFactory (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:10948:20)
       at _createProviderInstance$1 (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:10900:26)
       at resolveNgModuleDep (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:10882:17)
       at NgModuleRef_.get (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:12119:16)
       at resolveDep (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:12609:45)
       at createClass (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:12471:29)
       at createDirectiveInstance (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:12316:37),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      ReferenceError: navigator is not defined
          at getOS (C:\mynodeprojects\mean_project_start\node_modules\@ngx-share\core\bundles\ngx-share-core.umd.js:548:78)
          at new ShareButtons (C:\mynodeprojects\mean_project_start\node_modules\@ngx-share\core\bundles\ngx-share-core.umd.js:416:19)
          at ShareButtonsFactory (C:\mynodeprojects\mean_project_start\node_modules\@ngx-share\button\bundles\ngx-share-button.umd.js:137:12)
          at _callFactory (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:10948:20)
          at _createProviderInstance$1 (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:10900:26)
          at resolveNgModuleDep (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:10882:17)
          at NgModuleRef_.get (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:12119:16)
          at resolveDep (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:12609:45)
          at createClass (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:12471:29)
          at createDirectiveInstance (C:\mynodeprojects\mean_project_start\node_modules\@angular\core\bundles\core.umd.js:12316:37) },

### Desired functionality
Not to see any errors when running in a server side rendered environment.

### Mention any other details that might be useful
none

**Comment by stephencawood** [comment]
I'm getting the same error:  "ReferenceError: navigator is not defined at getOS"
Also on Angular Universal.

I looked at the code in lib/core/src/share.service.ts and I don't see where navigator is defined.

```

function getOS() {
--
116 | const userAgent = navigator.userAgent \|\| navigator.vendor \|\| (window \|\| global).opera;


```

**Comment by MurhafSousli** [comment]
Hey, guys. I just publish a beta release `@ngx-share@5.0.1-beta.0` to fix this issue.  please try it and let me know if it works

**Comment by MurhafSousli** [comment]
@Tatenda is the issue fixed?
