### ISSUE TITLE
variable '--button-color' is undefined and used without a fallback

### ISSUE THREAD

**Issue by mspriggs1** [MurhafSousli/ngx-sharebuttons#282]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

macOS(High Sierra)

### The log given by the failure

WARNING in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
(Emitted value instead of an instance of Error) postcss-custom-properties: /Users/martinspriggs/Dev/wels-mobile-pwa/src/styles.scss:80:3: variable '--button-color' is undefined and used without a fallback
NonErrorEmittedError: (Emitted value instead of an instance of Error) postcss-custom-properties: /Users/martinspriggs/Dev/wels-mobile-pwa/src/styles.scss:80:3: variable '--button-color' isundefined and used without a fallback
    at Object.emitWarning (/Users/martinspriggs/Dev/wels-mobile-pwa/node_modules/webpack/lib/NormalModule.js:117:16)
    at result.warnings.forEach (/Users/martinspriggs/Dev/wels-mobile-pwa/node_modules/postcss-loader/lib/index.js:149:49)
    at Array.forEach (<anonymous>)
    at postcss.process.then (/Users/martinspriggs/Dev/wels-mobile-pwa/node_modules/postcss-loader/lib/index.js:149:27)
    at <anonymous>
 @ ./src/styles.scss 4:14-191
 @ multi ./src/styles.scss ./src/theme.scss

### Mention any other details that might be useful

This appears as a warning and seems to have no affect on the functionality. Just cluttering up build process.

**Comment by mspriggs1** [comment]
manually added the variable to styles.scss
