### ISSUE TITLE
Icons not imported in ssr

### ISSUE THREAD

**Issue by ishan123456789** [MurhafSousli/ngx-sharebuttons#326]
#### I am submitting a

- [x] Question

#### What is the expected behavior?
The icons should be imported in SSR too.

#### What is the current behavior?

```
havemybooks@0.0.0 serve:ssr E:\xampp\htdocs\havemybooks
> node dist/server

Node Express server listening on http://localhost:4000
FontAwesome: Could not find icon with iconName=facebook-f and prefix=fab
FontAwesome: Could not find icon with iconName=twitter and prefix=fab
ERROR { Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'fontawesome-webfont.woff2'
Error: Cannot match any routes. URL Segment: 'fontawesome-webfont.woff2'
    at ApplyRedirects.noMatchError (E:\xampp\htdocs\havemybooks\dist\server.js:145929:16)
    at CatchSubscriber.selector (E:\xampp\htdocs\havemybooks\dist\server.js:145910:29)
    at CatchSubscriber.error (E:\xampp\htdocs\havemybooks\dist\server.js:29486:31)
    at MapSubscriber.Subscriber._error (E:\xampp\htdocs\havemybooks\dist\server.js:20931:26)
    at MapSubscriber.Subscriber.error (E:\xampp\htdocs\havemybooks\dist\server.js:20905:18)
    at MapSubscriber.Subscriber._error (E:\xampp\htdocs\havemybooks\dist\server.js:20931:26)
    at MapSubscriber.Subscriber.error (E:\xampp\htdocs\havemybooks\dist\server.js:20905:18)
    at MapSubscriber.Subscriber._error (E:\xampp\htdocs\havemybooks\dist\server.js:20931:26)
    at MapSubscriber.Subscriber.error (E:\xampp\htdocs\havemybooks\dist\server.js:20905:18)
    at TapSubscriber._error (E:\xampp\htdocs\havemybooks\dist\server.js:31306:26)
    at resolvePromise (E:\xampp\htdocs\havemybooks\dist\server.js:943:31)
    at resolvePro
```

#### Which versions are you using for the following packages?

     Angular:  "^6.0.0",
    "@angular/platform-server": "^6.0.0",
    "@angular/pwa": "^0.6.8",
    "@angular/router": "^6.0.0",
    "@angular/service-worker": "^6.0.0",
    "@fortawesome/angular-fontawesome": "0.1.0-10",
    "@fortawesome/fontawesome-svg-core": "^1.2.2",
    "@fortawesome/free-brands-svg-icons": "^5.2.0",
    "@fortawesome/free-solid-svg-icons": "^5.2.0",
    "@ngx-share/button": "^6.0.1",
    "@ngx-share/buttons": "^6.0.1",
    "@ngx-share/core": "^6.0.1",

#### Is there anything else we should know?
I've imported icons.ts in the polyfills.ts it works fine when serving directly but gives the above error when using ssr.
Can you please help me with this as icons are not getting added here and also I want to remove this long error log.

**Comment by MurhafSousli** [comment]
Maybe `polyfills.ts` is excluded in SSR, try to move the code you put in `polyfills.ts` to `main.ts`

**Comment by ishan123456789** [comment]
Thanks a ton it fixed the problem
