### ISSUE TITLE
Share-button doesn't work for Angular 9 SSR part.

### ISSUE THREAD

**Issue by Ambitiont109** [MurhafSousli/ngx-sharebuttons#453]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
 No Errors
#### What is the current behavior?
- Warning: Entry point 'ngx-sharebuttons/icons' contains deep imports into 'C:/Users/Ambition/Downloads/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faFacebookF', ... 
- npm run dev:ssr
  ERROR Error: Property `icon` is required for `fa-icon`/`fa-duotone-icon` components.
    at faWarnIfIconSpecMissing (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:107755:11)
    at FaIconComponent.ngOnChanges (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:107838:20)
    at FaIconComponent.wrapOnChangesHook_inPreviousChangesStorage (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:73774:18)
    at callHook (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:52968:14)
    at callHooks (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:52928:17)
    at executeInitAndCheckHooks (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:52868:9)
    at refreshView (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:59357:21)
    at refreshEmbeddedViews (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:60735:17)
    at refreshView (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:59366:9)
    at refreshComponent (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:60789:13)

ERROR Error: Property `icon` is required for `fa-icon`/`fa-duotone-icon` components.
    at faWarnIfIconSpecMissing (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:107755:11)
    at FaIconComponent.ngOnChanges (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:107838:20)
    at FaIconComponent.wrapOnChangesHook_inPreviousChangesStorage (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:73774:18)
    at callHook (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:52968:14)
    at callHooks (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:52928:17)
    at executeInitAndCheckHooks (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:52868:9)
    at refreshView (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:59357:21)
    at refreshEmbeddedViews (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:60735:17)
    at refreshView (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:59366:9)
    at refreshComponent (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:60789:13)
 

#### Which versions are you using for the following packages?

Angular CLI: 9.1.7
Node: 12.13.0
OS: win32 x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cdk                      9.2.4
@angular/cli                      9.1.7
@ngtools/webpack                  9.1.7
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

#### Is there anything else we should know?
I just created the new blank angular 9 projects and added the 
    ShareButtonsModule.withConfig({debug:true}),
    ShareIconsModule
on app.module.ts. 
``` ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { ShareButtonsModule } from 'ngx-sharebuttons/buttons';
import { ShareIconsModule } from 'ngx-sharebuttons/icons';
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule.withServerTransition({ appId: 'serverApp' }),
    AppRoutingModule,
    ShareButtonsModule.withConfig({debug:true}),
    ShareIconsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```
And Used share-button simply on app.compoent.html.
Here is the raw data of app.compoent.html
``` html
<h4> Hello World!!! </h4>
<share-buttons [theme]="'default'" [description]="'description'" [title] = "'title'" [url] = "'https://www.google.com'"
              [include]="['facebook','twitter','telegram','whatsapp','sms','email']" [show]="6" [showIcon]="true"
              [showText]="false" [size]="-4" [autoSetMeta]="false">
            </share-buttons>
<router-outlet></router-outlet>

```

**Comment by MurhafSousli** [comment]
It seems that the errors thrown is caused by FontAwesome package, did you install the package?

**Comment by Ambitiont109** [comment]
Yes. I already installed them.
I can see the share buttons on the web browser.
However, I get such an error in the console.

**Comment by MurhafSousli** [comment]
Yes, can you upload the project and give me the link

**Comment by Ambitiont109** [comment]
[angular9-starter.zip](https://github.com/MurhafSousli/ngx-sharebuttons/files/4706063/angular9-starter.zip)
I uploaded the angular9-starter.zip
you can test by following command.
npm install
- npm run build:ssr & npm run serve:ssr
- npm run dev:ssr

**Comment by MurhafSousli** [comment]
You didn't mention that the app is working properly, the icons is shown without errors in the browser, the errors show only in the express console.

The code in ngx-sharebuttons source code looks fine, I have reported this to Angular FontAwesome repo, let's see what they say!

**Comment by Ambitiont109** [comment]
So, Is it related to the Angular FontAwesome Repository?

**Comment by Ambitiont109** [comment]
and what is this 
Warning: Entry point 'ngx-sharebuttons/icons' contains deep imports into 'C:/Users/Ambition/Downloads/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faFacebookF', ...

**Comment by MurhafSousli** [comment]
See [ShareIconModule](https://github.com/MurhafSousli/ngx-sharebuttons/blob/release/v8/projects/ngx-sharebuttons/icons/src/share-icons.module.ts) in `ngx-sharebuttons/icons`

If you like you can remove this module, and include the icons manually in your app, but you will still get the same errors in the console. the error is in `fa-icon` component itself, not from this package

**Comment by MurhafSousli** [comment]
@Ambitiont109 I've published a new release ngx-sharebuttons@8.0.0beta.6, please try it and confirm that it solved the issue

**Comment by Ambitiont109** [comment]
Then Do we also have to raise the issue in fa-icon packages?

**Comment by Ambitiont109** [comment]
> @Ambitiont109 I've published a new release `ngx-sharebuttons@8.0.0beta.6`, please try it and confirm that it solved the issue

OKay. I see. Let me try right now.

**Comment by Ambitiont109** [comment]
Hello! I have tried again. And got the below issue.
ERROR Error: Property `icon` is required for `fa-icon`/`fa-duotone-icon` components.
    at faWarnIfIconSpecMissing (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:107755:11)
    at FaIconComponent.ngOnChanges (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:107838:20)
    at FaIconComponent.wrapOnChangesHook_inPreviousChangesStorage (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:73774:18)
    at callHook (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:52968:14)
    at callHooks (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:52928:17)
    at executeInitAndCheckHooks (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:52868:9)
    at refreshView (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:59357:21)
    at refreshEmbeddedViews (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:60735:17)    at refreshView (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:59366:9)
    at refreshEmbeddedViews (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:60735:17)
ERROR Error: Property `icon` is required for `fa-icon`/`fa-duotone-icon` components.
    at faWarnIfIconSpecMissing (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:107755:11)
    at FaIconComponent.ngOnChanges (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:107838:20)
    at FaIconComponent.wrapOnChangesHook_inPreviousChangesStorage (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:73774:18)
    at callHook (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:52968:14)
    at callHooks (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:52928:17)
    at executeInitAndCheckHooks (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:52868:9)
    at refreshView (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:59357:21)
    at refreshEmbeddedViews (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:60735:17)    at refreshView (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:59366:9)

**Comment by MurhafSousli** [comment]
Can you try it with this repo? I added universal to the demo app, please clone this repo and change the branch to `release/v8`

**Comment by Ambitiont109** [comment]
Okay. I see.
Let  me try

**Comment by MurhafSousli** [comment]
@Ambitiont109 Can you please try to this repo, I've added Universal to the demo

After cloning the repo, try the following:

1. `git checkout releave/v8`
2. Build the library `npm run build`
3. Link the library `npm run link-lib`
4. Build the demo (SSR) `npm run build:ssr`
5. Serve the demo (SSR) `npm run serve:ssr`

Please ignore any warnings for now! let's make sure the errors are disappeared

**Comment by Ambitiont109** [comment]
Hello I checked your repository. And It doesn't get any error.
I will check my repository again!
I would much appreciate it if you also can check it on your side.

**Comment by Ambitiont109** [comment]
Hello.
Don't you know why It gets error on my project?
I used <share-buttons> in blank project.

**Comment by MurhafSousli** [comment]
I fixed it now, will release v8.0.0

**Comment by Ambitiont109** [comment]
Okay. I see.

**Comment by Ambitiont109** [comment]
Hello
Have you tested with the below command?
npm run build:ssr & npm run serve:ssr
I used 8.0.0 ngx-sharebuttons in my blank project(I already sent you above)
However, I got the below errors.
ode Express server listening on http://localhost:4000
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'ngsw-worker.js'
Error: Cannot match any routes. URL Segment: 'ngsw-worker.js'
    at router_ApplyRedirects.noMatchError (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3952159)
    at CatchSubscriber.selector (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3951815)
    at CatchSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:1215693)
    at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
    at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
    at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
    at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
    at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
    at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
    at ThrowIfEmptySubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
    at resolvePromise (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2195888)
    at resolvePromise (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2194865)
    at C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2197692
    at ZoneDelegate.invokeTask (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2186992)
    at Object.onInvokeTask (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2672712)
    at ZoneDelegate.invokeTask (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2186882)
    at Zone.runTask (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2179557)
    at drainMicroTaskQueue (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2190600)
    at ZoneTask.invokeTask (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2188641)
    at ZoneTask.options.useG.invoke (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2188406) {
  rejection: Error: Cannot match any routes. URL Segment: 'ngsw-worker.js'
      at router_ApplyRedirects.noMatchError (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3952159)
      at CatchSubscriber.selector (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3951815)
      at CatchSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:1215693)
      at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
      at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
      at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
      at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
      at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
      at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
      at ThrowIfEmptySubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: Error: Cannot match any routes. URL Segment: 'ngsw-worker.js'
        at router_ApplyRedirects.noMatchError (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3952159)
        at CatchSubscriber.selector (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3951815)
        at CatchSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:1215693)
        at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
        at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
        at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
        at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
        at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
        at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
        at ThrowIfEmptySubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
  },
  zone: Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true, maybeDelayChangeDetection: false },
    _zoneDelegate: ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular],
      _hasTaskCurrZone: [Circular]
    }
  },
  task: ZoneTask {
    _zone: Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: Error: Cannot match any routes. URL Segment: 'ngsw-worker.js'
          at router_ApplyRedirects.noMatchError (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3952159)
          at CatchSubscriber.selector (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3951815)
          at CatchSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:1215693)
          at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
          at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
          at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
          at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
          at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
          at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
          at ThrowIfEmptySubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function],
    invoke: [Function]
  }
}
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'ngsw.json'
Error: Cannot match any routes. URL Segment: 'ngsw.json'
    at router_ApplyRedirects.noMatchError (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3952159)
    at CatchSubscriber.selector (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3951815)
    at CatchSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:1215693)
    at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
    at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
    at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
    at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
    at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
    at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
    at ThrowIfEmptySubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
    at resolvePromise (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2195888)
    at resolvePromise (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2194865)
    at C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2197692
    at ZoneDelegate.invokeTask (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2186992)
    at Object.onInvokeTask (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2672712)
    at ZoneDelegate.invokeTask (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2186882)
    at Zone.runTask (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2179557)
    at drainMicroTaskQueue (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2190600)
    at ZoneTask.invokeTask (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2188641)
    at ZoneTask.options.useG.invoke (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:2188406) {
  rejection: Error: Cannot match any routes. URL Segment: 'ngsw.json'
      at router_ApplyRedirects.noMatchError (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3952159)
      at CatchSubscriber.selector (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3951815)
      at CatchSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:1215693)
      at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
      at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
      at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
      at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
      at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
      at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
      at ThrowIfEmptySubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: Error: Cannot match any routes. URL Segment: 'ngsw.json'
        at router_ApplyRedirects.noMatchError (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3952159)
        at CatchSubscriber.selector (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3951815)
        at CatchSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:1215693)
        at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
        at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
        at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
        at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
        at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
        at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
        at ThrowIfEmptySubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
  },
  zone: Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true, maybeDelayChangeDetection: false },
    _zoneDelegate: ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular],
      _hasTaskCurrZone: [Circular]
    }
  },
  task: ZoneTask {
    _zone: Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: Error: Cannot match any routes. URL Segment: 'ngsw.json'
          at router_ApplyRedirects.noMatchError (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3952159)
          at CatchSubscriber.selector (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:3951815)
          at CatchSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:1215693)
          at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
          at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
          at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
          at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
          at MapSubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
          at MapSubscriber.error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969262)
          at ThrowIfEmptySubscriber._error (C:\Users\Ambition\Downloads\angular9-starter\dist\angular9-starter\server\main.js:1:969477)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function],
    invoke: [Function]
  }
}
